### ISSUE TITLE
download directory

### ISSUE THREAD

**Issue by zhichaoLii** [se-bastiaan/TorrentStream-Android#18]
when i download a directory(include several files), but it only downloaded one file and tell me it done

**Comment by se-bastiaan** [comment]
This library is not supposed to download multiple files.

**Comment by zhichaoLii** [comment]
Ok, I found the code and modify it, how can i selected some special files in the downloading directory for download ?

**Comment by se-bastiaan** [comment]
You can only select one file. Using `Torrent.setSelectedFileIndex(int)`
