### ISSUE TITLE
TorrentStream-Android is not working

### ISSUE THREAD

**Issue by leveychen** [se-bastiaan/TorrentStream-Android#27]
W/linker: /data/app/com.example.levey.magnet-2/lib/arm64/libjlibtorrent.so: unused DT entry: type 0x6ffffffe arg 0x187228
W/linker: /data/app/com.example.levey.magnetr-2/lib/arm64/libjlibtorrent.so: unused DT entry: type 0x6fffffff arg 0x3

the cpu is armv7a powered by Mediatek

**Comment by se-bastiaan** [comment]
This says nothing about what is happening? You have to be more specific.

**Comment by 4gus71n** [comment]
Do you have the torrent link that you used?
