### ISSUE TITLE
Openssl update.

### ISSUE THREAD

**Issue by diaconuliviu85** [se-bastiaan/TorrentStream-Android#3]
Good morning.
First you doi the thanks for your work , good work.
You can please update openssl ?
Thank you. a greeting

**Comment by se-bastiaan** [comment]
There is no OpenSSL in this library.

**Comment by diaconuliviu85** [comment]
unzip -p torrentstream.apk | strings | grep "OpenSSL"

OpenSSL 1.0.2d 9 Jul 2015

everything is possible , just use an old openssl and should be changed ASAP . I appreciate your time and please offered to do an adjustment will adapt when the new version jlibtorrent

**Comment by se-bastiaan** [comment]
I'm pretty sure it's jlibtorrent. The underlaying LibTorrent uses OpenSSL. You've got till July, enough time.

```
Beginning  
July 11, 2016, Google Play will block publishing of any new apps or updates  
that use older versions of OpenSSL. If you're using a 3rd party library  
that bundles OpenSSL, you'll need to upgrade it to a version that bundles  
OpenSSL 1.02f/1.01r or higher.
```
