### ISSUE TITLE
error from change lib ...0.24

### ISSUE THREAD

**Issue by diaconuliviu85** [se-bastiaan/TorrentStream-Android#9]
Hi , i am change from now libtorrentVersion 1.1.0.24, and i am receive this error

E:\AndroidStudioProjects\VideoPlayerStreaming\library\src\main\java\com\github\se_bastiaan\torrentstream\listeners\DHTStatsAlertListener.java
Error:(31, 45) error: cannot find symbol method getSwig()
E:\AndroidStudioProjects\VideoPlayerStreaming\library\src\main\java\com\github\se_bastiaan\torrentstream\listeners\TorrentAddedAlertListener.java
Error:(27, 49) error: cannot find symbol method getSwig()
Error:(32, 22) error: cannot find symbol method getType()
Error:(33, 18) error: cannot find symbol variable TORRENT_ADDED
E:\AndroidStudioProjects\VideoPlayerStreaming\library\src\main\java\com\github\se_bastiaan\torrentstream\Torrent.java
Error:(376, 41) error: cannot find symbol method getSwig()
Error:(377, 41) error: cannot find symbol method getSwig()
Error:(383, 22) error: cannot find symbol method getType()
Error:(384, 18) error: cannot find symbol variable PIECE_FINISHED
Error:(387, 18) error: cannot find symbol variable BLOCK_FINISHED
Error:Execution failed for task ':library:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by diaconuliviu85** [comment]
i am changed from libtorrentVersion = '1.1.0.22' and is work fine.  but if exchange from ...0.24 , all code from de library is in error.

**Comment by jackwakefield** [comment]
I've fixed these in #10, but you can change the gradle dependency to the following until it's merged

`compile 'com.github.jackwakefield:TorrentStream-Android:09f33eeef4'`

**Comment by se-bastiaan** [comment]
Sorry! I totally forgot to fix this. Thanks @jackwakefield.
